Write long commands on several lines for clarity

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -51,8 +51,20 @@ jobs:
   fast_finish: true
 # command to install dependencies
 install:
-    - if [[ "$TRAVIS_PYTHON_VERSION" == "2"* ]] || [[ "$TRAVIS_PYTHON_VERSION" == "pypy"* ]]; then pip install -r requirements-py2.txt; else pip3 install -r requirements-py3.txt; fi
+  - if [[ "$TRAVIS_PYTHON_VERSION" == "2"* ]] || [[ "$TRAVIS_PYTHON_VERSION" == "pypy"* ]]; then \
+      pip install -r requirements-py2.txt; \
+    else \
+      pip3 install -r requirements-py3.txt; \
+    fi
 # command to run tests
 script:
   # pypy3 segfaults if running all tests in the same process
-  - if [[ "$TRAVIS_PYTHON_VERSION" == "pypy"* ]]; then FAILURES=(); find tests -type f -name "*.py" | while read s; do ( [ ! -x "$s" ] && nosetests -v "$s" ) || FAILURES+=("$s"); done; [ "${#FAILURES[@]}" -ne 0 ] && ( echo "Tests failed in the following files:\n\t${FAILURES[@]}"; exit 1 ); else nosetests tests; fi
+  - if [[ "$TRAVIS_PYTHON_VERSION" == "pypy"* ]]; then \
+      FAILURES=(); \
+      find tests -type f -name "*.py" | while read s; do \
+        ( [ ! -x "$s" ] && nosetests -v "$s" ) || FAILURES+=("$s"); \
+      done; \
+      [ "${#FAILURES[@]}" -ne 0 ] && ( echo "Tests failed in the following files:\n\t${FAILURES[@]}"; exit 1 ); \
+    else \
+      nosetests tests; \
+    fi
