Run each test in its own process on PyPy*
The previous commit was sufficient for PyPy3 and to fix tests.test_py3.TestSniffer.test_sniffer() where csv_py3.Sniffer().sniff(contents).__dict__ on some Python versions where it was empty. This commit tries to fix segfault issues on PyPy by breaking the tests in yet more processes.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -96,11 +96,22 @@ install:
     fi
 # command to run tests
 script:
-  # pypy3 segfaults if running all tests in the same process
+  # pypy2 and pypy3 segfault on Travis CI if running all tests in the same process
   - >
-    if [[ "$TRAVIS_PYTHON_VERSION" == "pypy"* ]]; then
+    if [[ "$TRAVIS_PYTHON_VERSION" == "pypy" ]]; then
+      nosetests --collect-only -v tests 2>&1
+        | grep -e 'ok$'
+        | while read func class etc; do
+          class="${class//[()]/}";
+          class="${class%.*}:${class##*.}";
+          python3 -m nose -v "$class.$func";
+        done || ( echo "$s" >> "script-failures.log" );
+      if [ -e "script-failures.log" ]; then
+        exit 1;
+      fi;
+    elif [[ "$TRAVIS_PYTHON_VERSION" == "pypy3" ]]; then
       find tests -type f -name "*.py" | while read s; do
-        ( [ ! -x "$s" ] && nosetests -s -v --no-byte-compile "$s" ) || ( echo "$s" >> "script-failures.log" );
+        ( [ ! -x "$s" ] && nosetests --no-byte-compile -s -v "$s" ) || ( echo "$s" >> "script-failures.log" );
       done;
       if [ -e "script-failures.log" ]; then
         exit 1;
